### ISSUE TITLE
Name `Aux` not allowed on Windows

### ISSUE THREAD

**Issue by lorenzovngl** [Piano-Walrus/termCalc-app#2]
I noticed a problem on Windows.
The name `Aux` and [other names](https://help.interfaceware.com/v6/windows-reserved-file-names) are reseverd on Windows, so this operating system don't accept file or folder with these names. In fact, when I clone this repository on my local machine, the file [`Aux.java`](https://github.com/Piano-Walrus/termCalc-app/blob/main/app/src/main/java/com/mirambeau/termcalc/Aux.java) is renamed in `_Aux.java`, but the java compiler throws an error because it's expected that a public class has the same name of its file.

Could it be considered to choose another name for the class `Aux`? For example, `Auxl`?

**Comment by Piano-Walrus** [comment]
Yeah, I realized this pretty early into the development of the app, but since I mainly develop in Ubuntu and MacOS, typing/saying "Aux" has become second nature to me at this point. However, as painful as it was to finally be forced to rename this file, I've pushed a commit where I changed the name to Ax, and then changed another similar class from Ax to Aux (but that second class is in BetterMath.java, so it shouldn't be an issue as it is not a file name). If this still presents an issue, just open another issue and I'll rename the second Aux class as well.

**Comment by lorenzovngl** [comment]
This issue is partially solved because the class `Aux` in `BetterMath.java` is compiled in `Aux.class`, so the problem is equal to the previous. Also, you can't rename the second class to `Ax` (contained in `BetterMath.java`) as you did for the first beacause the compiler will throw an error because a file named `Ax.class` already exists.

**Comment by Piano-Walrus** [comment]
Yeah, I was afraid that might happen. I've pushed a new commit that renames the second class as well, so now neither one is named Aux, and they both have different names. That should fix the issue.
